# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Solution.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog

import trans as ts

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(997, 540)
        Dialog.setStyleSheet("background-color: rgb(75, 150, 115)")
        self.lbl_feasible = QtWidgets.QLabel(Dialog)
        self.lbl_feasible.setGeometry(QtCore.QRect(420, 80, 171, 131))
        self.lbl_feasible.setStyleSheet("color: rgb(0,0,0);\n"
"background-color: rgb(255, 255, 255);\n"
"font: 75 12pt \"Times New Roman\";\n"
"font: 12pt \"Impact\";")
        self.lbl_feasible.setText("")
        self.lbl_feasible.setObjectName("lbl_feasible")
#         self.btnPrint = QtWidgets.QPushButton(Dialog,clicked=lambda :self.Printer())
#         self.btnPrint.setGeometry(QtCore.QRect(410, 440, 121, 41))
#         self.btnPrint.setStyleSheet("background-color: rgb(85, 255, 127);\n"
# "font: 75 12pt \"Candara\";")
#         self.btnPrint.setObjectName("btnPrint")
        self.lblcost = QtWidgets.QLabel(Dialog)
        self.lblcost.setGeometry(QtCore.QRect(160, 80, 151, 131))
        self.lblcost.setStyleSheet("color: rgb(0,0,0);\n"
"background-color: rgb(255, 255, 255);\n"
"font: 75 12pt \"Times New Roman\";\n"
"font: 12pt \"Impact\";")
        self.lblcost.setText("")
        self.lblcost.setObjectName("lblcost")
        self.lb_rows = QtWidgets.QLabel(Dialog)
        self.lb_rows.setGeometry(QtCore.QRect(190, 320, 111, 51))
        self.lb_rows.setText("")
        self.lb_rows.setObjectName("lb_rows")
        self.lb_Supply = QtWidgets.QLabel(Dialog)
        self.lb_Supply.setGeometry(QtCore.QRect(190, 240, 111, 51))
        self.lb_Supply.setText("")
        self.lb_Supply.setObjectName("lb_Supply")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(50, 40, 141, 31))
        self.label.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(310, 40, 211, 31))
        self.label_2.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(50, 250, 131, 31))
        self.label_3.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(50, 340, 131, 31))
        self.label_4.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);")
        self.label_4.setObjectName("label_4")
        self.lbl_final_Tableau = QtWidgets.QLabel(Dialog)
        self.lbl_final_Tableau.setGeometry(QtCore.QRect(740, 80, 171, 131))
        self.lbl_final_Tableau.setStyleSheet("color: rgb(0,0,0);\n"
"background-color: rgb(255, 255, 255);\n"
"font: 75 12pt \"Times New Roman\";\n"
"font: 12pt \"Impact\";")
        self.lbl_final_Tableau.setText("")
        self.lbl_final_Tableau.setObjectName("lbl_final_Tableau")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(630, 40, 141, 31))
        self.label_5.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(340, 300, 171, 41))
        self.label_6.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);")
        self.label_6.setObjectName("label_6")
        self.lbl_Optimal = QtWidgets.QLabel(Dialog)
        self.lbl_Optimal.setGeometry(QtCore.QRect(530, 300, 381, 41))
        self.lbl_Optimal.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);")
        self.lbl_Optimal.setText("")
        self.lbl_Optimal.setObjectName("lbl_Optimal")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        #self.btnPrint.setText(_translate("Dialog", "Print"))
        self.lb_rows.setStyleSheet(_translate("Dialog", "color: rgb(0,0,0);\n"
"background-color: rgb(255, 255, 255);\n"
"font: 75 12pt \"Times New Roman\";\n"
"font: 12pt \"Impact\";"))
        self.lb_Supply.setStyleSheet(_translate("Dialog", "color: rgb(0,0,0);\n"
"background-color: rgb(255, 255, 255);\n"
"font: 75 12pt \"Times New Roman\";\n"
"font: 12pt \"Impact\";"))
        self.label.setText(_translate("Dialog", "Cost Values"))
        self.label_2.setText(_translate("Dialog", "Basic Feasible Solution:"))
        self.label_3.setText(_translate("Dialog", "Supply Values"))
        self.label_4.setText(_translate("Dialog", "Demand Values"))
        self.label_5.setText(_translate("Dialog", "Final Tableau:"))
        self.label_6.setText(_translate("Dialog", "Optimal Solution:"))
        self.lblcost.setText(str(ts.cost))
        self.lbl_feasible.setText(str(ts.np.array(ts.bfs, dtype=object)))
        self.lbl_final_Tableau.setText(str(ts.solution))
        self.lbl_Optimal.setText(str(ts.get_total_cost(ts.cost, ts.solution)))
        self.lb_Supply.setText(str(ts.model_supply))
        self.lb_rows.setText(str(ts.model_demand))
    # def Printer(self):
    #     option=QFileDialog.getSaveFileName(object,'Save File')
    #     file=open(option,'w')
    #     text=self.lbl_final_Tableau.text()
    #     file.write(text)
    #     file.close()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

