# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QFileInfo
from PyQt5.QtPrintSupport import QPrinter, QPrintDialog
from PyQt5.QtWidgets import QDialog, QFileDialog


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl1 = QtWidgets.QLabel(self.centralwidget)
        self.lbl1.setGeometry(QtCore.QRect(9, 9, 782, 504))
        self.lbl1.setText("")
        self.lbl1.setObjectName("lbl1")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(100, 450, 601, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnPrint = QtWidgets.QPushButton(self.horizontalLayoutWidget,clicked=lambda :self.PrintFile())
        self.btnPrint.setObjectName("btnPrint")
        self.horizontalLayout.addWidget(self.btnPrint)
        self.btnPrint_Preview = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnPrint_Preview.setObjectName("btnPrint_Preview")
        self.horizontalLayout.addWidget(self.btnPrint_Preview)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Printing a Document"))
        self.btnPrint.setText(_translate("MainWindow", "Print"))
        self.btnPrint_Preview.setText(_translate("MainWindow", "PrintPreview"))


    def PrintFile(self):
        printer=QFileDialog.getSaveFileName(MainWindow,"Export PDF","",'PDF files (.pdf);;All files()')
        if printer!='':
            if QFileInfo(printer).suffix()=="":
                printer+='.pdf'
                printer1=QPrinter(QPrinter.HighResolution)
                printer1.setOutputFormat(QPrinter.PdfFormat)
                printer1.setOutputFileName(printer)
                self.lbl1.document().print_(printer1)
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())